name: release

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/

      - name: Set up fontTools
        run: pip3 install fonttools[woff]

      - name: Set up AFDKO
        run: |
          pip3 install afdko
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Clean up distribution files
        run: |
          rm -rf dist/*.bdf
          rm -rf dist/*.ttf
          rm -rf dist/*.woff2

      - name: Convert to BDF font
        run: |
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o dist/Galmuri11.bdf src/Galmuri11.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o dist/Galmuri11-Bold.bdf src/Galmuri11-Bold.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o dist/Galmuri11-Condensed.bdf src/Galmuri11-Condensed.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o dist/Galmuri9.bdf src/Galmuri9.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o dist/Galmuri7.bdf src/Galmuri7.kbits

      - name: Convert to TrueType font and compress to WOFF2
        run: |
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o tGalmuri11.ttf src/Galmuri11.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o tGalmuri11-Bold.ttf src/Galmuri11-Bold.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o tGalmuri11-Condensed.ttf src/Galmuri11-Condensed.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o tGalmuri9.ttf src/Galmuri9.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o tGalmuri7.ttf src/Galmuri7.kbits
          makeotf -mf files/FontMenuNameDB -f tGalmuri11.ttf -ff files/g11.fea -o dist/Galmuri11.ttf -osbOn 6 -addn
          makeotf -mf files/FontMenuNameDB -f tGalmuri11-Bold.ttf -ff files/g11b.fea -o dist/Galmuri11-Bold.ttf -osbOn 5 -addn
          makeotf -mf files/FontMenuNameDB -f tGalmuri11-Condensed.ttf -ff files/g11c.fea -o dist/Galmuri11-Condensed.ttf -osbOn 6 -addn
          makeotf -mf files/FontMenuNameDB -f tGalmuri9.ttf -ff files/g9.fea -o dist/Galmuri9.ttf -osbOn 6 -addn
          makeotf -mf files/FontMenuNameDB -f tGalmuri7.ttf -ff files/g7.fea -o dist/Galmuri7.ttf -osbOn 6 -addn
          otf2otc -o dist/Galmuri.ttc dist/Galmuri11.ttf dist/Galmuri11-Bold.ttf dist/Galmuri11-Condensed.ttf dist/Galmuri9.ttf dist/Galmuri7.ttf
          fonttools ttLib.woff2 compress dist/Galmuri11.ttf
          fonttools ttLib.woff2 compress dist/Galmuri11-Bold.ttf
          fonttools ttLib.woff2 compress dist/Galmuri11-Condensed.ttf
          fonttools ttLib.woff2 compress dist/Galmuri9.ttf
          fonttools ttLib.woff2 compress dist/Galmuri7.ttf

      - name: Update npm package version
        run: |
          python files/version.py files/g11.fea package.json
          python files/version.py files/g11.fea package-lock.json

      - name: Get npm package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Clean up Temporary Files
        run: rm -rf dist/*_mod.bdf

      - name: Make zip
        run: zip -r Galmuri-v${{ steps.package-version.outputs.current-version }}.zip dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Galmuri-v${{ steps.package-version.outputs.current-version }}.zip
          tag_name: 'v${{ steps.package-version.outputs.current-version }}'

      - name: Clean up Temporary Files
        run: |
          rm -rf Galmuri-v*.zip
          rm -rf tGalmuri*.ttf

      - name: Publish to npm
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
